### ISSUE TITLE
Put blackbox-0.72.6 Under the 'Releases'

### ISSUE THREAD

**Issue by ghost** [bbidulock/blackboxwm#14]
Hi,

A lot of people might just be lazy like I am, and only look under the ```Releases``` for new versions;

https://github.com/bbidulock/blackboxwm/releases

But today I was a little less lazy and started reading to realize you have 0.72.6 released.

By the way, off topic here, but Openbox has not seen any development in 2 years, maybe the dust can be dusted off Blackbox and this WM brought back into some really serious development.

I hope maybe it's more compliant with tint2 now?

https://gitlab.com/o9000/tint2

Thanks for the new release, keep it up, I hope it will become even more active...

**Comment by bbidulock** [comment]
Sorry, 0.72.6 is just a git version.  Next release will be 0.73.

Openbox is a fine window manager.  It is very NetWM/EWMH and XDG compliant.  Maybe that makes it about as boring as Metacity, but it likely does not need much "fixing".
