### ISSUE TITLE
0.72.6 - Tint2 Sits Above Toolbar

### ISSUE THREAD

**Issue by ghost** [bbidulock/blackboxwm#15]
Hi,

I've been hoping support for tint2 might work, but I notice that tint2, when the toolbar is disabled, tint2 will still sit on the desktop, just above where the toolbar is normally located.

I guess tint2 seems to think the toolbar is located below, therefore it places itself above it.

Hopefully this is something you can work out, I'd really love to use tint2 in blackbox.

Thanks

**Comment by Geyup** [comment]
Something else I noticed, I have 4 desktops for tint2, and if I have a app minimized on any of the desktops, then move to another desktop with my keyboard shortcut keys, like how you move from desktop to desktop in Blackbox, or you can click one of the sections in tint2 to move, the minimized app will jump to that desktop with you.

If the apps/windows aren't minimized to tint2, this doesn't happen.

So I can make a bug report over this too if you want?

Thanks

**Comment by bbidulock** [comment]
I hate tint2: it behaves poorly with many window managers.  Fixing it requires fixing tint2, not blackbox.

**Comment by 0pLuS0** [comment]
Hi,

Have there been any changes in tint2 since this Github issue was reported in 2019, where tint2 and BB are working better together?

It's my understanding, if it still behaves poorly with many window managers, is that it was only made for Openbox.

It also looks like the project is dead at the moment, they said ```Frozen``` what ever the flip that's suppose to mean.

https://gitlab.com/o9000/tint2

I only use Openbox, and I've never had an issue with it in Openbox, but that's another dead project, such is the life in Linux, they come, they go.

**Comment by bbidulock** [comment]
Too bad: Openbox was a really good light-weight window manager with a lot of NetWM/EWMH support.  @CtrlAltLilith appears to have a bit of a carry-on fork going.

**Comment by 0pLuS0** [comment]
What is Mikachu? The name seems somewhat familiar hmm...

I didn't realize anyone had forked Openbox and was working on it, I wish bloody Google was giving better search results on Openbox, because I've been searching for years.

Is this the only fork/development of Openbox that you are aware of?

THANKS

**Comment by bbidulock** [comment]
There are forks under danakj/openbox too, but CtrlAltLilith looks best.  I would start a carry-on fork myself if I could collect enough maintainer patches to make a good start of it and could attract a few interested developers.  Improving autostart behavior and generating root application menus from XDG specifications would be a good start I think.

**Comment by 0pLuS0** [comment]
I tried CtrlAltLilith, unfortunately not good, the original Openbox is still much better.

Now it seems like Tint2 developement might be dead, the code is frozen, not sure what's going on with it.

Oh well, I'm still on Openbox 3.6.1 and tint2 and it's still chugging along.

Now we need a great SpaceFM fork too...

Oh the live of Linux with the death of so many projects, hard to keep a box shiny/smooth and alive... :/

**Comment by CtrlAltLilith** [comment]
> I tried CtrlAltLilith, unfortunately not good, the original Openbox is still much better.
> 
> Now it seems like Tint2 developement might be dead, the code is frozen, not sure what's going on with it.
> 
> Oh well, I'm still on Openbox 3.6.1 and tint2 and it's still chugging along.
> 
> Now we need a great SpaceFM fork too...
> 
> Oh the life of Linux with the death of so many projects, hard to keep a box shiny/smooth and alive... :/

what issue did you run into?

**Comment by 0pLuS0** [comment]
> > I tried CtrlAltLilith, unfortunately not good, the original Openbox is still much better.
> > Now it seems like Tint2 developement might be dead, the code is frozen, not sure what's going on with it.
> > Oh well, I'm still on Openbox 3.6.1 and tint2 and it's still chugging along.
> > Now we need a great SpaceFM fork too...
> > Oh the life of Linux with the death of so many projects, hard to keep a box shiny/smooth and alive... :/
> 
> what issue did you run into?

It's been almost a year, and I don't remember looking back.

Regualr Openbox doesn't give me any problems, and I don't see any changes in the fork, that I need the benefit of at the moment.

Also Slackware 15.0 uses autoconf-2.69, so I can't build it at the moment to check it out again. If things ever change in the future with various Linux changes/updates, etc., that might start causing Openbox issues, I'll certainly keep an eye out on your project. It's to bad the original developers let it go.
