### ISSUE TITLE
Conky name appears in toolbar

### ISSUE THREAD

**Issue by ghost** [bbidulock/blackboxwm#16]
In 0.72.6 in the center of the toolbar, where you normally see the name of windows, conky has it's name listed there.

These are the options I use for conky, is there anyway to get the name removed from the toolbar?

conky.config = {
override_utf8_locale = false,
background = true,
use_xft = true,
font = 'noto sans:size=10.5',
xftalpha = 0.8,
out_to_console = false,
out_to_stderr = false,
update_interval = 3.0,
total_run_times = 0,
draw_shades = false,

own_window = true,
own_window_class = 'Conky',
own_window_type = 'desktop',
own_window_transparent = true,
own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',

own_window_argb_visual = true,

minimum_width = 1920,
maximum_width = 1920,

double_buffer = true,
default_color = '5370c3',
color1 = 'e0cdc3',

alignment = 'top_middle',
gap_y = 5,
no_buffers = true
}

conky.text = [[
${alignc}${color}CPU1: ${color1}${cpu cpu0}%   \
${color}CPU2: ${color1}${cpu cpu1}%   \
${color}CPU3: ${color1}${cpu cpu2}%   \
${color}CPU4: ${color1}${cpu cpu3}% - ${freq}MHz - ${hwmon 0 temp 1} °C   \
${color}GPU: ${color1}${nvidia gpuutil}% - ${nvidia temp} °C   \
${color}RAM: ${color1}${mem} - $memperc%   \
${color}SSD: ${color1}${fs_free /} free   \
${color}LAN: ${color1}${addr eth0} - ${downspeed eth0} down - ${upspeed eth0} up   \
${color}UP: ${color1}$uptime_short \
]]

**Comment by bbidulock** [comment]
Conky manual page says:

own_window_hints ...
    ... If you use own_window_type override, window manager hints have no meaning and are ignored.

So, you own_window_type='desktop' causes your own_window_hints='...skip_taskbar...' to be ignored.
