### ISSUE TITLE
0.73 release tarball and release notes missing

### ISSUE THREAD

**Issue by bsiegert** [bbidulock/blackboxwm#20]
Looking at the "Releases" page, I see that blackbox 0.73 has been released, but there is no official (.tar.xz) source code file. Could you provide one please? I would like to update the package in pkgsrc.

**Comment by bbidulock** [comment]
Fixed.  I also released a 0.74 release that includes the latest full screen non-maximized window patch.

**Comment by bsiegert** [comment]
Excellent, thanks!
