### ISSUE TITLE
autogen.sh doesn't work correctly with all gettext versions (e.g. 0.20.1)

### ISSUE THREAD

**Issue by dhgutteridge** [bbidulock/blackboxwm#23]
Two related things here. I can see that commit "handle gettext 0.19.5.1" https://github.com/bbidulock/blackboxwm/commit/f57b1019c32082a20e379186475d588ef5d8c784 added some sed to only match the first three parts of a gettext version number, presumably to work around the fact autopoint would fail to find infrastructure files for "0.19.5.1". Unfortunately, this doesn't work with gettext 0.20.1, which is the same situation.

I also don't follow in general why it's necessary to override the gettext version required for a non-developer build invocation? (In downstream packaging for pkgsrc.org, I've just commented out those particular lines for now. https://github.com/NetBSD/pkgsrc/commit/29e0ba461fe0f366d3763fbb661dc530c4f76ee0.)

**Comment by bbidulock** [comment]
Try the updated autogen.sh.

Also, autogen.sh is only for developer builds from git.  Non-developers should be building the release tarballs instead and only running the already created ./configure script.

**Comment by dhgutteridge** [comment]
There is no ./configure script provided in recent release tarballs, e.g. 0.74.

**Comment by dhgutteridge** [comment]
Your change to autogen.sh works for me, thanks!

**Comment by bbidulock** [comment]
Yes, the blackbox-0.74.tar.xz tarball has a configure script.

Regardless, please close if resolved.

**Comment by dhgutteridge** [comment]
It's resolved for me, closing issue. (Sorry for the delay, I was on vacation.)
