### ISSUE TITLE
BB 0.75 fails to build in centos8

### ISSUE THREAD

**Issue by rosset** [bbidulock/blackboxwm#25]
gettext-devel-0.19.8.1-17.el8.x86_64

+ cd blackbox-0.75
+ autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.20 but this version
               is older. Please upgrade to gettext-0.20 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
error: Bad exit status from /var/tmp/rpm-tmp.NTRWh7 (%build)

**Comment by bbidulock** [comment]
Your distro's gettext is old.  You can get around this by executing ./autogen.sh before anything else.  This will edit AM_GNU_GETTEXT_VERSION for you and perform an autoreconf -iv too.

**Comment by rosset** [comment]
working fine, thanks, blackbox 0.76 will beavailable in EPEL8 soon
