### ISSUE TITLE
Build crash with --enable-shared

### ISSUE THREAD

**Issue by eribertomota** [bbidulock/blackboxwm#26]
Dear upstream,

I am trying update the Debian package to 0.76 version. We use --enable-shared option. The final result is:

```
/usr/bin/ld: Window.o: undefined reference to symbol 'XShapeCombineShape'
/usr/bin/ld: /lib/x86_64-linux-gnu/libXext.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Thanks in advance.

Regards,

Eriberto

**Comment by bbidulock** [comment]
I don't have any problems building with --enable-shared option, so must be something more than just that.
