### ISSUE TITLE
Possibly A Few Good Patches?

### ISSUE THREAD

**Issue by Geyup** [bbidulock/blackboxwm#3]
I was looking through the patches applied, and I found these others online I didn't notice added, not sure if any are needed...

Please check if you might need these, I'm not sure if any are useful.

bbdock.patch
https://gist.github.com/Geyup/e7be8e57aa546b854ec7

asneeded.patch
https://gist.github.com/Geyup/75d8a3e994999e87f665

configure.patch
https://gist.github.com/Geyup/61fa53b66f3627578f9d

fix-spelling-errors.diff
https://gist.github.com/Geyup/e99c429ce8b6a3bd508e

focus.diff
https://gist.github.com/Geyup/a32d45c94f7ab3b4c1c7

manpage-tidyup.diff
https://gist.github.com/Geyup/dc4c972a44333f9ae505

This one below really caught my attention, because when using conky and you click on 'Restart' in the menu, conky will then redraw over itself creating what looks like multiple instances and it looks like a mess. I applied the patch and it worked! It appears there are argb issues without the patch.

argb-visual.patch
http://www.t2-project.org/packages/blackbox.html

There is also a problem when using a composite manager, I use compton, when switching workspaces the numbers on the toolbar don't change, this patch fixes that.

 workspace-label.patch
http://www.t2-project.org/packages/blackbox.html

**Comment by bbidulock** [comment]
All of these patches were already applied (about  a year ago), except the last two, which I have applied separately.

**Comment by Geyup** [comment]
Hello bbidulock, this is really great to see you here and this project is still alive!
I can't begin to tell you how happy I am, LOL...

Thanks for keeping this alive!

**Comment by Geyup** [comment]
Oh, forgot to mention, I found these two patches online one for bbkeys, not sure if they are of any good., not sure what the other one is for.

bbkeys.patch
https://gist.github.com/Geyup/496bd182f54a05f94e9c

patch-src_Netclient_cpp.patch
https://gist.github.com/Geyup/babeca52b4d6bef295c8

**Comment by Geyup** [comment]
I I just pulled from git today, ```argb-visual.patch & workspace-label.patch```, are in the latest git? Because when I compiled it, these bugs appear again, as if the patches have not been applied...

By the way BIG THANKS for keeping blackbox alive!

**Comment by bbidulock** [comment]
Yes, they are applied.

**Comment by Geyup** [comment]
It looks like you didn't apply all of the patch?
