### ISSUE TITLE
Build new blackbox on BSD/UNIX os

### ISSUE THREAD

**Issue by j4n3b** [bbidulock/blackboxwm#30]
Hello;
I was very happy to see some people work on and use great blackbox.
I tried to build it under bsd but get this error     `date: illegal option -- -` :
```
./autogen.sh
date: illegal option -- -
usage: date [-jnRu] [-r seconds] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: running: autopoint --force
Copying file po/Makefile.in.in
autoreconf-2.69: running: aclocal --force -I m4
/usr/local/share/aclocal/libxosd.m4:9: warning: underquoted definition of AM_PATH_LIBXOSD
/usr/local/share/aclocal/libxosd.m4:9:   run info Automake 'Extending aclocal'
/usr/local/share/aclocal/libxosd.m4:9:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
configure.ac:84: error: possibly undefined macro: AC_DISABLE_SHARED
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf-2.69: /usr/local/bin/autoconf-2.69 failed with exit status: 1
```
this error is due to the fact that the script is using BSD version of tools .
I am sure of this one.
the gnuversion of tools are in /usr/local/bin.
Could you help me?

**Comment by dhgutteridge** [comment]
Hi,

If I may jump in here, I'm not a maintainer for this project, but I am a downstream maintainer of blackbox for NetBSD's distribution purposes, so I've a few comments. You don't say which "BSD" you're using, which may help contextualize this.

You may find the patch I just submitted as [ https://github.com/bbidulock/blackboxwm/pull/31]( https://github.com/bbidulock/blackboxwm/pull/31) relevant for you. It's necessary to compile on NetBSD.

It's unclear why you're running autogen.sh? Does the configure script provided in the distribution tarball (presently [https://github.com/bbidulock/blackboxwm/releases/download/0.76/blackbox-0.76.tar.lz](https://github.com/bbidulock/blackboxwm/releases/download/0.76/blackbox-0.76.tar.lz)) not work for you? It's sufficient for NetBSD (which we then apply our packaging overrides to).

Regards,

Dave

**Comment by bbidulock** [comment]
autogen.sh is really only intended for building a development copy directly from a github clone.
