### ISSUE TITLE
blackbox @0.75 does not build on Big Sur, macOS 11.0.1, because of "Undefined symbols for architecture x86_64: "_libiconv"

### ISSUE THREAD

**Issue by ballapete** [bbidulock/blackboxwm#34]
It's reported first here: https://trac.macports.org/ticket/61485. The cause is that lib/Makefile does not add libiconv to target libbt:

--- lib/Makefile.in~    2019-09-06 11:55:04.000000000 +0200
+++ lib/Makefile.in     2020-11-16 00:36:15.000000000 +0100
@@ -458,7 +458,7 @@
                        Util.hh                                         \
                        XDG.hh

-libbt_la_LIBADD = $(XFT_LIBS) $(XEXT_LIBS) $(X11_LIBS)
+libbt_la_LIBADD = $(XFT_LIBS) $(XEXT_LIBS) $(X11_LIBS) $(LTLIBICONV)
 pkgconfigdir = $(libdir)/pkgconfig
 nodist_pkgconfig_DATA = libbt.pc
 all: all-am

**Comment by bbidulock** [comment]
Mac problem, fixed downstream.
