### ISSUE TITLE
Iconified Window Disable?

### ISSUE THREAD

**Issue by Geyup** [bbidulock/blackboxwm#4]
Hi,

If I'm not mistaken, the orignal Blackbox already has a Workspaces popup when you double click both left & right mouse button, at least that's how I always remember it, and I see it's still in this fork 0.71.1.

So I'd like to be able to disable this left click window and remove it, is that possible? I'm assuming this is a new feature you added, do you have a compile time --disable option? If not, can you please make one to disable this at compile.

For me this left click window gets in the way and pops up a lot when I need to left click on something.

Or maybe a Menu option to enable and disable between which one a person wants to use? Hmm

I've attached a screen shot of the original middle click window.

![iconified](https://cloud.githubusercontent.com/assets/13072581/12692728/0a24eb12-c6f3-11e5-9d32-068ff7bd178b.jpg)

**Comment by bbidulock** [comment]
It was commit 13ed4c09498e1f144135025508ea42a6605e65f5 that added this button action.  It is compiled in.  Revert this commit if you want to undo it.

**Comment by Geyup** [comment]
Ahh ok, great...

Maybe if you get time, you can make a compile option for it, like; --disable-option?

thank you

**Comment by Geyup** [comment]
Here's a patch I made to revert back;

https://gist.github.com/Geyup/5120d7886574529a8f7a
