### ISSUE TITLE
blackbox crashes desktop icon managers

### ISSUE THREAD

**Issue by wandrien** [bbidulock/blackboxwm#49]
blackbox crashes a desktop icon manager on start up or when switching blackbox styles from the menu.

Tested applications:

* [`pcmanfm --desktop`](https://github.com/lxde/pcmanfm) : crash
* [`stuurman-desktop`](https://github.com/sde-gui/stuurman-desktop/issues/12) : crash
* [`caja --force-desktop`](https://mate-desktop.org/) : crash
* [`xfdesktop`](https://www.xfce.org/) : crash
* [`rox -S`](https://rox.sourceforge.net/) : seems to work

`pcmanfm` and `stuurman-desktop` emit the message:

```
Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```

`caja` prints the following:

```
(caja:183925): Gdk-WARNING **: 15:30:58.837: The program 'caja' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 19573 error_code 9 request_code 62 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

`xfdesktop` exits without any messages.

**Comment by bbidulock** [comment]
I think that you need to configure BB to not manage the background of the root window to use a desktop manager.  The default is for BB to manage the root background.
