### ISSUE TITLE
Man page blackbox.1.gz becomes unzipped...

### ISSUE THREAD

**Issue by Geyup** [bbidulock/blackboxwm#5]
Hi,

I'm running Slackawre 14.1 x86_64 and Slack gunzips man pages, and this is my compile and options I have regarding man for my build script;

--mandir=/usr/man \

if [ -d $PKG/usr/man ]; then
  ( cd $PKG/usr/man
    for manpagedir in $(find . -type d -name "man*") ; do
      ( cd $manpagedir
        for eachpage in $( find . -type l -maxdepth 1) ; do
          ln -s $( readlink $eachpage ).gz $eachpage.gz
          rm $eachpage
        done
        gzip -9 *.?
      )
    done
  )
fi

I'm not sure why, but I've noticed that in /usr/man/man1 blackbox1.gz ends up unzipped as blackbox.1, and then I end up with both files.

I've been messing with blackbox compiling it over for the past few days, and everytime I delete blackbox.1 it still appears, not sure what's causing this.

**Comment by bbidulock** [comment]
Not sure how to help with this.

**Comment by Geyup** [comment]
I'll keep my eye on what I'm doing and report back...

**Comment by Geyup** [comment]
Oh it appears that you need to install Blackbox into the system in oder for bbkeys to find libbt, so this is why I was seeing the man page like this...

**Comment by bbidulock** [comment]
So, can you close this?
