### ISSUE TITLE
Even Debian unstable only has Blackbox 0.70.1-39 in its repositories ...

### ISSUE THREAD

**Issue by its-thomas** [bbidulock/blackboxwm#51]
See [https://packages.debian.org/search?keywords=blackbox](https://packages.debian.org/search?keywords=blackbox)

Latest Blackbox Maintenance Release is 0.77.

As a Debian stable user, I would be happy to have more recent Blackbox packages in the official repositories.

**Comment by bbidulock** [comment]
I haven't been following blackbox on Debian.  I gave up on Debian/Ubuntu for Archlinux long ago.  Archlinux has the current version from this fork, and so does SuSE last I checked.  Maybe talk to Debian maintainers?

**Comment by its-thomas** [comment]
Package maintainers seem to be  the [Debian QA Group](https://qa.debian.org/developer.php?email=packages%40qa.debian.org). 

Maybe you could write a short notice? (Probably has more weight when the repository owner contacts them instead  of some random user.)
