### ISSUE TITLE
Handbrake Gui Flickers In Blackbox

### ISSUE THREAD

**Issue by Geyup** [bbidulock/blackboxwm#6]
Hi,

```My Specs;```
Slackware 14.1 x86_64
Blackbox 0.71.1
nvidia-driver-352.63
xorg-server-1.14.3
handbrake 0.9.9

I'm not sure what's causing this, I've never seen this before, only in Blackbox, the original 0.70.1 and your fork.

When I start handbrake the right side of the window flickers really bad.

I have compton the composite manager, but this happens with it running, or not.

I created a video so you can watch this.

http://www29.zippyshare.com/v/inMVUnG6/file.html

**Comment by bbidulock** [comment]
Do you have the dock on the right?

**Comment by Geyup** [comment]
Sorry what dock?

I'm using tint2 in Blackbox...

**Comment by bbidulock** [comment]
The window (typically on the right) that contains windowmaker dockapps.

**Comment by Geyup** [comment]
Sorry you confused me there, it's been a long time since using blackbox, so for a second I was thinking, does blackbox have a dock, so I wasn't sure what dock/app you were talking about.

No I'm not using any dock apps, just running only tint2...

**Comment by Geyup** [comment]
For any Slackware users of 14.1, alienbob's build script, there are problems with it.

I changed to using the slackbuilds.org build script for handbrake and now it's working good! :)
