### ISSUE TITLE
bbkeys seg fault

### ISSUE THREAD

**Issue by Geyup** [bbidulock/blackboxwm#7]
I just pulled from git today and compile 0.71.2 and when I run bbkeys I get a seg fault at the command line. In the last version, 0.71.1 bbkeys was working ok.

bbkeys: ScreenHandler: in findSupportingWM.
bbkeys: ScreenHandler: first readSupportingWMCheck succeeded.
bbkeys: ScreenHandler: second readSupportingWMCheck worked.
bbkeys: ScreenHandler: first try at getting wmName failed.
bbkeys: ScreenHandler: couldn't get wm's name.  letting it slide this time....
bbkeys: ScreenHandler: Found compatible window manager: [beats the heck out of me] for screen: [0].
bbkeys: ScreenHandler: Supported atoms: [45].

**Comment by bbidulock** [comment]
You have something seriously wrong.  I get:

bbkeys: ScreenHandler: in findSupportingWM.
bbkeys: ScreenHandler: first readSupportingWMCheck succeeded.
bbkeys: ScreenHandler: second readSupportingWMCheck worked.
bbkeys: ScreenHandler: Found compatible window manager: [Blackbox 0.71.2] for screen: [0].
bbkeys: ScreenHandler: Supported atoms: [69].

**Comment by Geyup** [comment]
Slackware has a buold script, ```blackbox.SlackBuild``` that I'm using for compiling and I haven't changed anything with it.

http://mirrors.slackware.com/slackware/slackware64-current/source/xap/blackbox/

So I'm not sure how 0.71.1 could work find and then 0.71.2 doesn't... hmm

**Comment by Geyup** [comment]
I originally ran git clone previously, then the other day ran git pull and compiled it, and ran into the problems. All I can assume is something in the pull somehow screwed up.

Because today I deleted the directory and ran git clone over and started fresh, compiled and it now works...

hmm odd
