### ISSUE TITLE
Question/Request - Centering feh UI?

### ISSUE THREAD

**Issue by Geyup** [bbidulock/blackboxwm#8]
Hi bbidulock,

I use feh to set wallpapers in Blackbox and Openbox. In Openbox I can use a cmd in the rc.xml which will center the UI, but in Blackbox the ```Window Placement``` setting doesn't work, I have it on center with nothing happening.

Do you know how I can get the feh UI to center, or if this is not possible in blackbox, maybe you can do something to change/fix this?

This is the entry I have for it in the menu;
```
[submenu] (Wallpaper)
    [exec] (Feh)                  {feh -Tbgpreview "/home/foo/Wallpaper/"} 
  [end]
```
Here's a screen shot, it always opens up in the upper left of the screen when I open it.

![feh](https://cloud.githubusercontent.com/assets/13072581/13031924/457b8ac8-d2d7-11e5-87d1-b66f8091429e.jpg)

**Comment by bbidulock** [comment]
Feh is worse than tint2.  It is not even setting ICCCM 2.0 window manager hints (or any other property for that matter).  Openbox likely accomodates broken applications,  but compare the size.  There are lightweight alternatives to feh that are far more compliant.

**Comment by Geyup** [comment]
I use the rc.xml in openbox to center feh, wasn't sure if there was something in blackbox that did the trick too...

```rc.xml entry in openbox```

<application name="feh">
      <position force="yes">
        <x>center</x>
        <y>center</y>
      </position>
      <maximized>no</maximized>
      <decor>no</decor>
    </application>

**Comment by Geyup** [comment]
I forgot to ask you, what lightweight alternatives to feh that are far more compliant, are you talking about?
